In [149]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score,accuracy_score,confusion_matrix
from sklearn.decomposition import PCA
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.manifold import MDS
from sklearn.preprocessing import Imputer,StandardScaler,MinMaxScaler, OneHotEncoder
from sklearn.pipeline import make_pipeline
import seaborn as sns
from __future__ import division
%matplotlib inline

In [150]:
X = pd.read_csv('S&P500_2017.csv')
X = X.drop(['Date'],axis=1)

In [174]:
X.head()

A        AAL         AAP        AAPL       ABBV        ABC  \
0  46.074703  45.816051  170.237915  113.847588  59.784031  80.855621   
1  46.679256  46.211868  171.634933  113.720161  60.626999  82.862099   
2  46.124260  45.410336  171.515182  114.298462  61.086800  81.902901   
3  47.561314  45.726990  169.269974  115.572708  61.105961  82.999107   
4  47.709969  46.587898  169.170197  116.631294  61.508286  83.664680   

         ABT         ACN        ADBE        ADI    ...             XL  \
0  37.982937  114.158501  103.480003  70.577911    ...      36.900692   
1  38.284462  114.432961  104.139999  70.431908    ...      37.027840   
2  38.615170  112.717552  105.910004  69.419624    ...      36.607288   
3  39.665661  114.001671  108.300003  69.692154    ...      36.568165   
4  39.626755  112.727356  108.570000  70.023094    ...      35.952015   

        XLNX        XOM       XRAY        XRX        XYL        YUM  \
0  57.513260  86.670731  58.296070  26.833357  48.875042  61.848686   
1  57.094593  85.717155  58.773418  27.845938  49.603493  62.073734   
2  56.403305  84.439362  58.007671  27.729099  49.150673  62.279217   
3  57.493786  84.391678  57.967899  27.300703  48.806133  63.032623   
4  57.503525  82.999451  58.146900  27.144920  48.599411  63.208748   

          ZBH       ZION        ZTS  
0  102.513084  42.586197  53.118965  
1  103.455551  43.197666  53.634392  
2  104.120262  42.497429  53.455975  
3  104.130180  42.773582  53.624477  
4  106.154053  42.310051  53.475800  

[5 rows x 503 columns]

In [162]:
r = 0.035/365
n = 10000

In [163]:
Times = [(t1,t1+np.random.choice(range(1,30))) for t1 in [np.random.choice(range(220))for _ in range(n)] ]

In [164]:
M=X.fillna(X.mean())
M = M.pct_change()
Z = pd.DataFrame(columns=M.columns)
Z = Z.T
Z['Mean'] = M.mean()
Z['Std'] = M.std()
Z['Skew'] = M.skew()
Z['Kurt'] = M.kurt()

$$K=S_0e^{rt}$$

In [165]:
Y = pd.DataFrame(columns=['Mean','Std','Skew','Kurt','I','F','D'],index=range(n))
for i in range(n):
    ran = np.random.choice(503)
    t = (Times[i][1]-Times[i][0])/365
    S0 = X.T.iloc[ran][Times[i][0]]
    K = S0*np.e**(r*t)
    St =  X.T.iloc[ran][Times[i][1]] 
    d=  (K <=St)*1
    Y.iloc[i]=list(Z.iloc[ran])+[Times[i][0],Times[i][1],d]

In [175]:
Y.head()

Mean       Std      Skew       Kurt    I    F  D
0  0.001158  0.007678  0.517933   2.649848  166  174  0
1  0.001479  0.008063  0.947642   6.732996    6   30  1
2  0.001127  0.008552  1.544926  12.869869   38   47  0
3  0.000951  0.014758  2.549030  17.848326  113  142  0
4  0.000065  0.014792  0.772190   4.060008  111  128  1

In [176]:
for col in Y.columns:
    Y[col] = Y[col].apply(pd.to_numeric, errors='coerce')

In [177]:
W = Y[['Mean','Std','Skew','Kurt','I','F']]
y = Y[['D']]

In [178]:
Xt,Xv,yt,yv =train_test_split(W,y,train_size=0.7)
for d in [Xt,Xv,yt,yv]:
    print d.shape

(7000, 6)
(3000, 6)
(7000, 1)
(3000, 1)


In [179]:
def metricas(model,Xt,Xv,yt,yv):
    print roc_auc_score(y_score=model.predict_proba(Xt)[:,1],y_true=yt)
    print roc_auc_score(y_score=model.predict_proba(Xv)[:,1],y_true=yv)
    print accuracy_score(y_pred=model.predict(Xt),y_true=yt)
    print accuracy_score(y_pred=model.predict(Xv),y_true=yv)
    print confusion_matrix(y_pred=model.predict(Xt),y_true=yt)
    print confusion_matrix(y_pred=model.predict(Xv),y_true=yv)

In [171]:
model =LogisticRegression()
model.fit(Xt,yt)
metricas(model,Xt,Xv,yt,yv)

0.554037974926
0.543487030249
0.598142857143
0.599666666667
[[  92 2713]
 [ 100 4095]]
[[  50 1157]
 [  44 1749]]


In [182]:
from sklearn.tree import DecisionTreeClassifier
param_grid = dict(criterion=['gini','entropy'],
                 max_depth=range(1,11),
                 min_samples_split = range(100,210,10)
                 )
model = DecisionTreeClassifier()
grid = GridSearchCV(cv=10,n_jobs=-1,scoring='roc_auc',
                    estimator=model,
                    param_grid=param_grid)


grid.fit(W,y)

print grid.best_estimator_
print grid.best_params_
print grid.best_score_

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=110,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
{'min_samples_split': 110, 'criterion': 'entropy', 'max_depth': 10}
0.670380251541


In [183]:
model = grid.best_estimator_
metricas(model,Xt,Xv,yt,yv)

0.757255467865
0.741980544167
0.705
0.684666666667
[[1500 1290]
 [ 775 3435]]
[[ 634  588]
 [ 358 1420]]


In [185]:
from xgboost.sklearn import XGBClassifier

In [189]:
xgb = XGBClassifier()
xgb.fit(W,y)
metricas(xgb,Xt,Xv,yt,yv)

0.73857988745
0.728217355605
0.686714285714
0.668333333333
[[1215 1575]
 [ 618 3592]]
[[ 506  716]
 [ 279 1499]]
